#wrute a compose for stack aut db book borrow app
services:
  db:
   image: yashu565656/pythonlinapp:databaseimage1.0
   deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
   ports:
      - "3306:3306"
   networks:
     - mynetwork    

  auth_service:
    image: yashu565656/pythonlinapp:authimage1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - db

  borrow_service:
    image: yashu565656/pythonlinapp:borrowimage1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on:
      - db

  book_service:
    image: yashu565656/pythonlinapp:bookimage1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on:
      - db

  app:
    image: yashu565656/pythonlinapp:appimage1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth_service
      - borrow_service
      - book_service

networks:
  mynetwork:
    driver: overlay  
